### ISSUE TITLE
Interesting file conflict on linux

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#27]
I just noticed an interesting problem when running examples of brian2genn on our linux server "lancing". Because @mstimberg had run other examples before, ptxas was unable to overwrite his /tmp/runner.cubin file with my own and failed. I am not sure why this temporary file ends up in /tmp and without any modifier that would make it unique.

**Comment by mstimberg** [comment]
Maybe a change I did to `brian2genn` has something to do with it. If you use `set_device('genn', directory=None)`, then it will create a new temporary directory for this run (using `tempfile.mkdtemp()`). This is done in the test suite and the advantage is that for the C++ standalone target it allows to run several tests in parallel (which would otherwise overwrite each others' files). Of course this is not really relevant to `brian2genn`, since running several tests in parallel that each try to use the GPU is certainly not a good idea. Nevertheless, I think the temp directory is a better target than the test directory because the latter might be part of a system-wide installation where the user has no write access.
All that said, those directories are made to be unique (they have names such as `/tmp/tmpjCJ_HE`), but maybe there is something in `brian2genn` or `GeNN` which uses the parent directory of that directory?

**Comment by tnowotny** [comment]
@jamesturner246 , can you have a look at this? We can chat independently, but I am a bit mystified where runner.cubin is coming from in the first place and why it is not removed during linking.

**Comment by jamesturner246** [comment]
I know why it's there. It's from the dry-run compile step. I'll change it
so it's just deleted afterwards, rather than
 being saved to the temp directory, which should solve your problem.

Cheers,
James.

**Comment by jamesturner246** [comment]
Should work fine now. Let me know if not.
