### ISSUE TITLE
Failing brian2 test: test_synapses.test_vectorisation_STDP_like

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#28]
The test `test_synapses.test_vectorisation_STDP_like` fails when brian2genn is run in GPU mode. I have investigated the source of the problem and it comes down to the following problem:
Within the test, (1) a pre-synaptic neuron variable is incremented in the pre-synaptic code and (2) a post-synaptic neuron variable is incremented by post-sunaptic code. In this particular example, this is done on a sparse synaptic connection.
Because the synapse updates are done in parallel for post-synaptic neurons in case 1 and along pre-synaptic spikes in case 2, both lead to race conditions on the target neuron variables; the correct solution would be to use `atomicAdd` and I have verified by manual substitution of `atomicAdd` in the generated code that this fixes the problem.
To permanently fix the problem may be more difficult. @mstimberg, @thesamovar : what kind of actions on pre- and post-synaptic neuron variables are allowed in synaptic code in brian 2? I can see what you would expect for incrementing (like here) but it appears that an action like a simple value assignment  would have to lead to undefined behaviour? Also, other non-commuting operations should be undefined?

**Comment by thesamovar** [comment]
We actually do have a check for potentially undefined behaviour, and emit a warning or error (can't remember which) in that case. I seem to remember in an earlier version of brian2genn we had an explicit check for code of the form ``neuron_var += synaptic_var`` that was treated specially. Are we talking about some generalisation of that?

Also, ``atomicAdd`` may be very inefficient on medium density synaptic operations (but is good for very low density ones, see mine and Romain's paper on GPU spiking neural networks).

**Comment by tnowotny** [comment]
This problem arises where the "on_pre" modifies pre-synaptic neuron variables and "on_post" modifies post-synaptic neurons variables (somewhat unusual, the case we covered was "on_pre" changing post-synaptic vars). 
This  exposes a bit more general problem, where just giving full access to pre- and post-synaptic neuron variables in GeNN can lead to undefined behaviour due to race conditions. If you exclude truly undefined behaviour within Brian, then the expected code should only be +=, *=, -=, /= and equivalent, right? However, I am not sure how one would do a "atomicDivide" ...
As for efficiency: If one wants to allow these manipulations, there is no choice but to use atomic operations I believe.

**Comment by thesamovar** [comment]
Ah I get you. At a conference at the moment so can't think too deeply about it, so just a couple of points for now.

Yes, I think ultimately you'll only allow ``+=`` etc. however there could be relatively complex expressions on the RHS of the ``+=`` so you can't just consider ``v += w`` type cases.

There is a way to do atomic divide although I've forgotten how you do it now. There's not a single operation, but I think you can put an atomic lock on a memory location? Something like that anyway.

Do you mean that if you want to allow modifications of both pre AND postsynaptic variables you have to use atomic operations? Because if you're just going in one direction there's all sorts of tricks, right? (I guess probably GeNN is using some of them, and NeMo uses a whole lot of tricks for sparse propagation.)
