### ISSUE TITLE
v.dimension error

### ISSUE THREAD

**Issue by Vafa-Andalibi** [brian-team/brian2genn#40]
Hi, 

I just updated brian2, brian2genn and genn to latest version and when running my code I got an error about v.dimension stating dimension attribute doesn't exist. brian2genn's device.py line 614: 
```
                if isinstance(v, ArrayVariable):
                    try:
                        if isinstance(v, DynamicArrayVariable):
                            if v.dimension == 1:
```
So I checked and seems like it's changed to v.dim

**Comment by mstimberg** [comment]
Yes, indeed (the new name is not `dim` but `ndim`). I already have a fix for this in one of my branches (the best approach is to replace `v.dimension` by `getattr(v, 'dimension', v.ndim)` so that it works with the old and the new version). In general, we cannot guarantee to keep up `brian2genn` with the master branch of `brian2` in between releases (and we did not even do an official release of `brian2genn` yet...).

Thanks for opening the issue, anyway, it's important to not forget about this.

**Comment by Vafa-Andalibi** [comment]
How can I know which brian2 commit is compatible with latest brian2genn ?

**Comment by mstimberg** [comment]
> How can I find which brian2 commit is compatible with latest brian2genn ?

Normally, we'd guarantee that brian2genn releases are compatible with the most recent brian2 release at that time. However, as the readme file states, brian2genn "is still under development and has not yet been officially released", so this does not quite apply (we hope to do a release quite soon, though!). 
Either way, brian2genn should work fine with the latest brian2 release, i.e. 2.0.1. We cannot guarantee that it will always work with the latest brian2 commit on master (but we try not to break things unnecessarily, of course).
