### ISSUE TITLE
Expose more GeNN preferences in brian2genn

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#55]
When running on a cluster I need to make use of GeNN preferences 
```
    extern int autoChooseDevice; //!< Flag to signal whether the GPU device should be chosen automatically 
    extern int defaultDevice; //! default GPU device; used to determine which GPU to use if chooseDevice is 0 (off)
```
I would suggest to just make them brian preferences under ```devices.genn.XXX```
Does that sound like a good plan @mstimberg ?
They would then have to be translated into genn preferences through the model template I suggest.

**Comment by mstimberg** [comment]
> Does that sound like a good plan @mstimberg ?

Sounds very reasonable to me! Obviously we'd make the `autoChooseDevice` a boolean value instead of an int in the preference, but all this should be very straightforward. Do you want to do this, or should I? It should not be complicated but I cannot test things in detail due to the lack of a graphics card in my laptop...

**Comment by tnowotny** [comment]
yeah ... probably should have been a bool in the first place but let's not split hairs at this point. I will make a start and let you know how I get on.

**Comment by tnowotny** [comment]
I think this works now and is reasonable. Not sure whether I should make a pull request as yet as I am also making other changes for the benchmarking ... but you can also cherry-pick the last commit into the master if you want.
