### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#91]
I think brian2genn is generally not Python 3 compatible. I believe we might need to fix that when we get the chance.

**Comment by mstimberg** [comment]
It would indeed be nice to make the code in the repository Python-3 compatible so that you can easily use Python 3 for developing (we only recently did this for Brian). Just to make clear that Brian2GeNN can be *used* with Python 3 just fine, you only have to install it via `pip` (or directly using `setup.py`) – it will run the `2to3` tool during installation to convert the code.

**Comment by tnowotny** [comment]
this has been resolved by #100.
